export { GoodsByType,GoodsByTypeMobile } from "./GoodByTypes";
export { Home, HomeMob } from "./Home/Home";
export { FullPost,FullPostMobile } from "./FullInfo/FullPost";
export { AddPost } from "./AddPost";
export { Login } from "./Login";
export  {ShoppingCart, ShoppingCartMobile} from "./Cart";
export {PopularGoods,PopularGoodsM} from "./Popular";
export{Sale,SaleM} from "./Sale";
export {AboutCompany} from "./AboutCompany";
export {MakeOrder,MakeOrderM} from "./MakeOrder";
export {Refund} from "./Refund";
export {Contact} from "./Contact";
export {Delivery} from "./Delivery";
export {Payments} from "./Payments";
export {Questions} from "./Questions";
export {Certificates} from "./Certificates";
export {Reviews} from "./Reviews";