export { GoodsByType,GoodsByTypeMobile } from "./GoodByTypes";
export { Home, HomeMob } from "./Home/Home";
export { FullPost,FullPostMobile } from "./FullInfo/FullPost";
export { AddPost } from "./AddPost";
export { Registration } from "./Registration";
export { Login } from "./Login";
export  {ShoppingCart, ShoppingCartMobile} from "./Cart";
export {PopularGoods} from "./Popular";
export{Sale} from "./Sale";
export {AboutCompany} from "./AboutCompany";
export {Contact} from "./Contact";
export {MakeOrder,MakeOrderM} from "./MakeOrder";